version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.13.0-stretch
  working_directory: ~/workspace/code


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
  test: 
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: yarn test:unit
